version: "2.4"
services:
  db:
    image: mysql:8.0.19
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      # Do not initialize, otherwise scripts won run
      # MYSQL_DATABASE: poc_backend
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: mysql --protocol TCP --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'show databases;'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    ports:
      - "3307:3306"
  api:
    build:
      context: .
      dockerfile: ./src/docker/Dockerfile
    command: ["-jar", "-Djava.net.preferIPv4Stack=true", "/opt/app/service.jar", "-Sdev"]
    environment:
      DB_ADDR: db
      DB_PORT: 3306
      DB_DATABASE: poc_backend
      DB_USER: docker
      DB_PASSWORD: docker
      JDBC_PARAMS: "?useSSL=false"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"