CREATE SCHEMA `poc_backend` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE SCHEMA `poc_keycloak` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

GRANT ALL PRIVILEGES ON *.* TO 'docker'@'%' WITH GRANT OPTION;